name: .NET CI and CD pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup the .NET 9.0
        uses: actions/setup-dotnet@v1.2
        with:
          dotnet-version: 9.0
      - name: Restore the Dependencies
        run: dotnet restore
      - name: build the app
        run: dotnet build --no-restore
      - name: test the app
        run: dotnet test --no-build --verbosity normal
